name: HeatSeekingMissile
version: '1.0-SNAPSHOT'
main: me.sachin.heatSeekingMissile.HeatSeekingMissile
api-version: '1.21'
softdepend: [GangsPlus, Essentials]
commands:
  hsm:
    description: Heat Seeking Missile commands
    usage: /<command> [help|get|give|reload]
    aliases: [heatseekingmissile]
permissions:
  hsm.cmds:
    default: op
  hsm.get:
    default: op
  hsm.give:
    default: op
  hsm.reload:
    default: op