name: HeatSeekingMissile
version: '1.0-SNAPSHOT'
main: me.sachin.heatSeekingMissile.HeatSeekingMissile
api-version: '1.21'
commands:
  hsm:
    description: Heat Seeking Missile commands
    usage: /<command> [help|reload]
    permission: hsm.cmds
    aliases: [heatseekingmissile]
permissions:
  hsm.cmds:
    description: Ac